[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "meu-projeto"
version = "0.1.0"
dependencies = [
    "fastapi>=0.100",
    "uvicorn>=0.23",
    "sqlalchemy>=2.0",
    "python-dotenv>=1.0",
    "bcrypt>=4.0",
    "sqlalchemy-utils>=0.41",
    "psycopg2-binary>=2.9",
    "requests>=2.33.1",
    "pydantic[email]",
    "fastapi[standard]",
    "nanoid ==2.0.0",
    "tzdata",
    "fastapi-mail==1.4.1",
    "pynfe",
    "signxml",
    "openpyxl",
    "reportlab"
]

[project.optional-dependencies]
test = [
    "pytest>=9.0",
    "pytest-asyncio>=1.4",
    "pytest-playwright>=0.8",
    "playwright>=1.60",
    "httpx>=0.28",
]

[tool.setuptools]
packages = ["backend"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -v --strict-markers"
testpaths = [
    "tests",
]
python_files = ["test_*.py", "*_test.py"]
python_functions = ["test_*"]